version: '3.8'
services:
  test:
    build:
      context: .
    volumes:
      - .:/app
    command: invoke test
    networks:
      - app-network

  db:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    networks:
      - app-network

  docker_test:
    build:
      context: .
    volumes:
      - .:/app
    command: ["pytest", "tests/docker.py"]
    networks:
      - app-network

  api:
    build:
      context: .
    volumes:
      - .:/app
    command: ["pytest", "tests/tests.py"]
    networks:
      - app-network

networks:
  app-network: {}
